"""fase2_models_pricing_discounts_services

Revision ID: 362d6bf6a8ba
Revises: 436477826c59
Create Date: 2026-03-20 13:29:14.251681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '362d6bf6a8ba'
down_revision: Union[str, None] = '436477826c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE serviceunit AS ENUM ('MINUTO', 'EVENTO', 'M2');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
        """
    )
    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE discountrequeststatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
        """
    )
    serviceunit = postgresql.ENUM(
        "MINUTO", "EVENTO", "M2", name="serviceunit", create_type=False
    )
    discountrequeststatus = postgresql.ENUM(
        "PENDING", "APPROVED", "REJECTED", name="discountrequeststatus", create_type=False
    )

    op.create_table('quote_additional_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calculated_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['additional_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('quote_item_id', sa.UUID(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', discountrequeststatus, nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_item_id'], ['quote_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('additional_services', sa.Column('unit', serviceunit, nullable=False))
    op.add_column('additional_services', sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False))
    op.add_column('additional_services', sa.Column('factor', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('additional_services', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('additional_services', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('additional_services_tenant_id_fkey'), 'additional_services', type_='foreignkey')
    op.create_foreign_key(None, 'additional_services', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('additional_services', 'base_price')
    op.drop_column('additional_services', 'unit_type')
    op.drop_column('additional_services', 'uma_factor')
    op.drop_column('additional_services', 'is_active')
    op.add_column('pricing_rules', sa.Column('base_6h', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('pricing_rules', sa.Column('base_12h', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('pricing_rules', sa.Column('extra_hour_rate', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('pricing_rules', sa.Column('discount_threshold', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('pricing_rules', sa.Column('effective_from', sa.Date(), nullable=True))
    op.add_column('pricing_rules', sa.Column('effective_to', sa.Date(), nullable=True))
    op.execute(
        """
        UPDATE pricing_rules SET
          base_6h = price_6h,
          base_12h = price_12h,
          extra_hour_rate = price_extra_hour,
          discount_threshold = 0,
          effective_from = CURRENT_DATE
        """
    )
    op.alter_column(
        "pricing_rules",
        "base_6h",
        existing_type=sa.Numeric(precision=12, scale=4),
        nullable=False,
    )
    op.alter_column(
        "pricing_rules",
        "base_12h",
        existing_type=sa.Numeric(precision=12, scale=4),
        nullable=False,
    )
    op.alter_column(
        "pricing_rules",
        "extra_hour_rate",
        existing_type=sa.Numeric(precision=12, scale=4),
        nullable=False,
    )
    op.alter_column(
        "pricing_rules",
        "discount_threshold",
        existing_type=sa.Numeric(precision=5, scale=2),
        nullable=False,
    )
    op.alter_column(
        "pricing_rules",
        "effective_from",
        existing_type=sa.Date(),
        nullable=False,
    )
    op.drop_constraint(op.f('uq_pricing_rules_tenant_space'), 'pricing_rules', type_='unique')
    op.drop_column('pricing_rules', 'price_extra_hour')
    op.drop_column('pricing_rules', 'price_12h')
    op.drop_column('pricing_rules', 'price_6h')
    op.add_column('quote_items', sa.Column('uma_snapshot', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('quote_items', sa.Column('uma_snapshot_date', sa.Date(), nullable=True))
    op.add_column('quote_items', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('quote_items', sa.Column('subtotal_frozen', sa.Numeric(precision=12, scale=4), nullable=True))
    op.alter_column('quote_items', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.drop_column('quote_items', 'frozen_price')
    op.drop_column('quote_items', 'discount_justification')
    op.drop_column('quote_items', 'discount_pct')
    op.create_foreign_key(None, 'reservation_slots', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.add_column('uma_rates', sa.Column('effective_date', sa.Date(), nullable=True))
    op.execute(
        """
        UPDATE uma_rates SET effective_date = start_date::date
        WHERE effective_date IS NULL AND start_date IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE uma_rates SET effective_date = CURRENT_DATE
        WHERE effective_date IS NULL
        """
    )
    op.alter_column(
        "uma_rates",
        "effective_date",
        existing_type=sa.Date(),
        nullable=False,
    )
    op.alter_column('uma_rates', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.execute(
        "ALTER TABLE uma_rates ALTER COLUMN created_by TYPE uuid USING created_by::uuid"
    )
    op.create_unique_constraint('uq_uma_rate_effective_date_tenant', 'uma_rates', ['effective_date', 'tenant_id'])
    op.create_foreign_key(None, 'uma_rates', 'users', ['created_by'], ['id'])
    op.drop_column('uma_rates', 'start_date')
    op.drop_column('uma_rates', 'end_date')
    op.drop_column('uma_rates', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uma_rates', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('uma_rates', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('uma_rates', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'uma_rates', type_='foreignkey')
    op.drop_constraint('uq_uma_rate_effective_date_tenant', 'uma_rates', type_='unique')
    op.alter_column('uma_rates', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('uma_rates', 'value',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('uma_rates', 'effective_date')
    op.drop_constraint(None, 'reservation_slots', type_='foreignkey')
    op.add_column('quote_items', sa.Column('discount_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('quote_items', sa.Column('discount_justification', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quote_items', sa.Column('frozen_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.alter_column('quote_items', 'discount_amount',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('quote_items', 'subtotal_frozen')
    op.drop_column('quote_items', 'discount_percentage')
    op.drop_column('quote_items', 'uma_snapshot_date')
    op.drop_column('quote_items', 'uma_snapshot')
    op.add_column('pricing_rules', sa.Column('price_6h', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.add_column('pricing_rules', sa.Column('price_12h', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.add_column('pricing_rules', sa.Column('price_extra_hour', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_pricing_rules_tenant_space'), 'pricing_rules', ['tenant_id', 'space_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('pricing_rules', 'effective_to')
    op.drop_column('pricing_rules', 'effective_from')
    op.drop_column('pricing_rules', 'discount_threshold')
    op.drop_column('pricing_rules', 'extra_hour_rate')
    op.drop_column('pricing_rules', 'base_12h')
    op.drop_column('pricing_rules', 'base_6h')
    op.add_column('additional_services', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('additional_services', sa.Column('uma_factor', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('additional_services', sa.Column('unit_type', postgresql.ENUM('MINUTE', 'EVENT', 'M2', 'PIECE', name='unittype'), autoincrement=False, nullable=False))
    op.add_column('additional_services', sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'additional_services', type_='foreignkey')
    op.create_foreign_key(op.f('additional_services_tenant_id_fkey'), 'additional_services', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('additional_services', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('additional_services', 'created_at')
    op.drop_column('additional_services', 'factor')
    op.drop_column('additional_services', 'unit_price')
    op.drop_column('additional_services', 'unit')
    op.drop_table('discount_requests')
    op.drop_table('quote_additional_services')
    # ### end Alembic commands ###
