"""Add pricing rules real

Revision ID: 5b2da7c0de33
Revises: da117d71a22d
Create Date: 2026-03-19 23:21:04.241828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2da7c0de33'
down_revision: Union[str, None] = 'da117d71a22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('price_6h', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price_12h', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price_extra_hour', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'space_id', name='uq_pricing_rules_tenant_space')
    )
    op.create_index(op.f('ix_pricing_rules_space_id'), 'pricing_rules', ['space_id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_tenant_id'), 'pricing_rules', ['tenant_id'], unique=False)

    # Enable RLS
    op.execute("ALTER TABLE pricing_rules ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON pricing_rules
        USING (
            tenant_id::text = current_setting('app.current_tenant_id', true)
            OR current_setting('app.role', true) = 'SUPERADMIN'
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_rules_tenant_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_space_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    # ### end Alembic commands ###
