"""Add UMA snapshot and discounts for TASK-057

Revision ID: da117d71a22d
Revises: z9a0b1c2d3e4
Create Date: 2026-03-19 22:39:12.814656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da117d71a22d'
down_revision: Union[str, None] = 'z9a0b1c2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_tenant_id'), 'login_attempts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_table('additional_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit_type', sa.Enum('MINUTE', 'EVENT', 'M2', 'PIECE', name='unittype'), nullable=False),
    sa.Column('uma_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_services_tenant_id'), 'additional_services', ['tenant_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_tenant_id'), 'reconciliations', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_access_qr_tokens_reservation_id'), table_name='access_qr_tokens')
    op.create_unique_constraint(None, 'access_qr_tokens', ['reservation_id'])
    op.drop_index(op.f('idx_audit_actor'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_registro'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_tenant_tabla'), table_name='audit_log')
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_cfdi_documents_uuid_fiscal'), table_name='cfdi_documents', postgresql_where='(uuid_fiscal IS NOT NULL)')
    op.drop_index(op.f('ix_checklists_master_service_order_id'), table_name='checklists')
    op.drop_index(op.f('ix_contracts_provider_document_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_quote_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_evidence_requirements_estado'), table_name='evidence_requirements')
    op.drop_index(op.f('ix_evidence_requirements_master_service_order_id'), table_name='evidence_requirements')
    op.drop_index(op.f('ix_evidence_requirements_tenant_id'), table_name='evidence_requirements')
    op.drop_index(op.f('ix_expediente_documents_contract_id'), table_name='expediente_documents')
    op.drop_index(op.f('ix_expediente_documents_created_at'), table_name='expediente_documents')
    op.drop_index(op.f('ix_expediente_documents_reservation_id'), table_name='expediente_documents')
    op.drop_index(op.f('ix_expediente_documents_tenant_id'), table_name='expediente_documents')
    op.drop_index(op.f('ix_inventory_space_id_fecha'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_tenant_id'), table_name='inventory')
    op.drop_constraint(op.f('fk_inventory_reservation_id'), 'inventory', type_='foreignkey')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_master_service_orders_contract_id'), table_name='master_service_orders')
    op.drop_index(op.f('ix_master_service_orders_reservation_id'), table_name='master_service_orders')
    op.drop_index(op.f('ix_master_service_orders_status'), table_name='master_service_orders')
    op.drop_index(op.f('ix_master_service_orders_tenant_id'), table_name='master_service_orders')
    op.drop_index(op.f('ix_notification_log_reservation_type'), table_name='notification_log')
    op.drop_index(op.f('ix_payment_vouchers_reservation_id'), table_name='payment_vouchers')
    op.drop_index(op.f('ix_payment_vouchers_tenant_id'), table_name='payment_vouchers')
    op.drop_index(op.f('ix_portal_messages_enviado_at'), table_name='portal_messages')
    op.drop_index(op.f('ix_portal_messages_reservation_id'), table_name='portal_messages')
    op.drop_index(op.f('ix_portal_messages_tenant_id'), table_name='portal_messages')
    op.add_column('quote_items', sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('quote_items', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('quote_items', sa.Column('discount_justification', sa.Text(), nullable=True))
    op.add_column('quote_items', sa.Column('frozen_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_index(op.f('ix_quote_items_quote_id'), table_name='quote_items')
    op.drop_index(op.f('ix_quote_items_space_id'), table_name='quote_items')
    op.add_column('quotes', sa.Column('uma_snapshot_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('quotes', sa.Column('uma_snapshot_reference', sa.String(length=255), nullable=True))
    op.add_column('quotes', sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('quotes', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('quotes', sa.Column('discount_justification', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_quotes_lead_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_tenant_id'), table_name='quotes')
    op.drop_index(op.f('ix_reservations_space_fecha'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_tenant_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_service_order_items_checklist_id'), table_name='service_order_items')
    op.drop_index(op.f('ix_space_relationships_tenant_id'), table_name='space_relationships')
    op.drop_index(op.f('ix_spaces_tenant_id'), table_name='spaces')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_spaces_tenant_id'), 'spaces', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_space_relationships_tenant_id'), 'space_relationships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_service_order_items_checklist_id'), 'service_order_items', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_index(op.f('ix_reservations_tenant_id'), 'reservations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_reservations_space_fecha'), 'reservations', ['space_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_quotes_tenant_id'), 'quotes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index(op.f('ix_quotes_lead_id'), 'quotes', ['lead_id'], unique=False)
    op.drop_column('quotes', 'discount_justification')
    op.drop_column('quotes', 'discount_amount')
    op.drop_column('quotes', 'discount_pct')
    op.drop_column('quotes', 'uma_snapshot_reference')
    op.drop_column('quotes', 'uma_snapshot_value')
    op.create_index(op.f('ix_quote_items_space_id'), 'quote_items', ['space_id'], unique=False)
    op.create_index(op.f('ix_quote_items_quote_id'), 'quote_items', ['quote_id'], unique=False)
    op.drop_column('quote_items', 'frozen_price')
    op.drop_column('quote_items', 'discount_justification')
    op.drop_column('quote_items', 'discount_amount')
    op.drop_column('quote_items', 'discount_pct')
    op.create_index(op.f('ix_portal_messages_tenant_id'), 'portal_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_portal_messages_reservation_id'), 'portal_messages', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_portal_messages_enviado_at'), 'portal_messages', ['enviado_at'], unique=False)
    op.create_index(op.f('ix_payment_vouchers_tenant_id'), 'payment_vouchers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payment_vouchers_reservation_id'), 'payment_vouchers', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_notification_log_reservation_type'), 'notification_log', ['reservation_id', 'notification_type'], unique=True)
    op.create_index(op.f('ix_master_service_orders_tenant_id'), 'master_service_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_master_service_orders_status'), 'master_service_orders', ['status'], unique=False)
    op.create_index(op.f('ix_master_service_orders_reservation_id'), 'master_service_orders', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_master_service_orders_contract_id'), 'master_service_orders', ['contract_id'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_foreign_key(op.f('fk_inventory_reservation_id'), 'inventory', 'reservations', ['reservation_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_inventory_tenant_id'), 'inventory', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_space_id_fecha'), 'inventory', ['space_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_expediente_documents_tenant_id'), 'expediente_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_expediente_documents_reservation_id'), 'expediente_documents', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_expediente_documents_created_at'), 'expediente_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_expediente_documents_contract_id'), 'expediente_documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_evidence_requirements_tenant_id'), 'evidence_requirements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_evidence_requirements_master_service_order_id'), 'evidence_requirements', ['master_service_order_id'], unique=False)
    op.create_index(op.f('ix_evidence_requirements_estado'), 'evidence_requirements', ['estado'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_quote_id'), 'contracts', ['quote_id'], unique=True)
    op.create_index(op.f('ix_contracts_provider_document_id'), 'contracts', ['provider_document_id'], unique=False)
    op.create_index(op.f('ix_checklists_master_service_order_id'), 'checklists', ['master_service_order_id'], unique=False)
    op.create_index(op.f('ix_cfdi_documents_uuid_fiscal'), 'cfdi_documents', ['uuid_fiscal'], unique=True, postgresql_where='(uuid_fiscal IS NOT NULL)')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.create_index(op.f('idx_audit_tenant_tabla'), 'audit_log', ['tenant_id', 'tabla', 'registrado_at'], unique=False)
    op.create_index(op.f('idx_audit_registro'), 'audit_log', ['registro_id', 'registrado_at'], unique=False)
    op.create_index(op.f('idx_audit_actor'), 'audit_log', ['actor_id', 'registrado_at'], unique=False)
    op.drop_constraint(None, 'access_qr_tokens', type_='unique')
    op.create_index(op.f('ix_access_qr_tokens_reservation_id'), 'access_qr_tokens', ['reservation_id'], unique=True)
    op.drop_index(op.f('ix_reconciliations_tenant_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_additional_services_tenant_id'), table_name='additional_services')
    op.drop_table('additional_services')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_tenant_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
